INSERT INTO TipoVeiculo ([Codigo],[Tipo]) VALUES ((1),'Carro') , ((2),'Moto')

GO

INSERT INTO Usuarios ([Nome],[Login],[Senha]) VALUES ('ADMIN','admin','admin')

GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 1, '100', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 1, '100 Avant', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 1, '80', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 1, '80 Avant', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 1, '80 Cabriolet', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'Concours', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'D tracker x', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'ER 5', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'ER 6n', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'KLX', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'KX', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'KZ', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'Maxi II', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'Ninja', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'Versys', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'Voyager', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'Vulcan', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'Z 1000', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'Z 300', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'Z 650', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'Z 750', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'Z 800', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 20,	'Z 900', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Besta', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Bongo', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Cadenza', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Carens', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Carnival', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Cerato', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Ceres', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Clarus', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Grand Carnival', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Magentis', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Mohave', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Opirus', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Optima', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Picanto', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Quoris', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Rio', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Sephia', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Shuma', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Sorento', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Soul', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Sportage', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (1, 10, 'Stinger', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 17, 	'Apache', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 17, 	'Cityclass 200i', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 17, 	'Fiddle', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 17, 	'Horizon', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 17, 	'Kansas', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 17, 	'Laser', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 17, 	'Maxsym 400i', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 17, 	'Next', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 17, 	'Riva', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 17, 	'Roadwin', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 17, 	'Smart', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 17, 	'Speed', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 17, 	'Super', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 17, 	'Sym Citycom', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 17, 	'Zig', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'America Classic', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'BIZ 100', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'BIZ 110i', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'BIZ 125', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'C 100 Dream', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CB 1000R', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CB 1300', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CB 300R', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CB 400', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CB 450', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CB 500', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CB 600 (Hornet)', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CB 650', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CB 750', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CB 900', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CB Twister', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CBR 1000', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CBR 1100', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CBR 250R', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CBR 450', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CBR 500', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CBR 600', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CBR 650', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CBR 900', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CBR 929', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CBR 954', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CBX 150', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CBX 200', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CBX 250', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CBX 750', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CG 125', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CG 150', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CG 160', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CH 125 R', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CRF', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CRF 1000', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'CTX 700', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'Elite 125', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'Gold Wing', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'LEAD', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'Magna 750', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'ML 125', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'NC 700X', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'NC 750X', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'NX 150', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'NX 200', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'NX 350', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'NX 4 Falcon', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'NXR 125', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'NXR 150', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'NXR 160', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'PCX', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'POP', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'SH', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'Shadow', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'Shadow Am', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'Shadow Vt', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'Silver Wing', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'Super Hawk', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'TRX (Quadriciclo)', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'Valkyrie', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'VFR', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'VT 600', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'VTX', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'X-ADV', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'XL 1000', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'XL 125', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'Xl 250', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'XL 350', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'XL 700V', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'XLR 125', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'XLX 250', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'XLX 350', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'XR 200', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'XR 250', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'XR 650', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'XRE 190', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 7,  'XRE 300', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Address Ae', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Address Ag', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Bandit 1200', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Bandit 1200S', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Bandit 1250', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Bandit 1250S', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Bandit 600', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Bandit 600S', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Bandit 650', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Bandit 650S', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Boulevard', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Burgman', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Dl 1000', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Dl 650', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Dr 350', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Dr 650', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Dr 800', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Dr Z 400', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'En 125', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Freewind', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gladius', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gs 120', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gs 500', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gsr 125', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gsr 150i', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gsr 750A', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gsx 1100', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gsx 1250FA', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gsx 1300', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gsx 650F', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gsx 750', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gsx R 1000', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gsx R 1000 (25anos)', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gsx R 1100', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gsx R 1300', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gsx R 750', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gsx S 1000', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gsx S 1000FA', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Gsx S 750', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Hayabusa', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Inazuma', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Intruder', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Katana', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Lets II', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Marauder', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Rf 600', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Rf 900', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'RM-Z', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Savage', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'SV 650', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Tl 1000', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 18, 	'Vx 800cc', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Axis 90', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Bws 50', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Crypton', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Crypton 100', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Drag Star 1100', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Drag Star 650', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Drag Star Xvs 650', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Dt 180 Z', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Dt 200', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Fazer 250 ie', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Fjr 1300', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Fz 6 600', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Fz1', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Fz6', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Fz6 s', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Fzr 1000', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Fzr 600', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Grizzly', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Jog 50', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Jog Teen 50', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Magesty', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'MT 01', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'MT 03', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'MT 07', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'MT 09', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Neo', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'NMax', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Rd 125', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Rd 135', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Rd 350', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Rdz 125', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Rdz 135', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Royal Star 1300', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Tdm 225', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Tdm 850', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Tdm 900', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Tdr 180', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Tmax', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Trx 850', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'TT-R', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'V Max 1200', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'V Max 1700', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'V Star 1100 Classic', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Virago 750', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Wr', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Xj6 F', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Xj6 N', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Xjr 1200', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'XT 1200Z', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'XT 225', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'XT 600', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'XT 660', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Xtz 125 E', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Xtz 125 K', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Xtz 125 X', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Xtz 150 Crosser', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Xtz 250 Lander', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Xtz 750', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Xv 1100', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Xv 250 (Virago)', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Xv 535', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'Xvs Midnight', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'YBR 125', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'YBR 125 Factor', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'YBR 150 Factor', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'YFM', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'YS 150 Fazer', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'YS 250 Fazer', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'YZ', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'YZF 1000', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'YZF 600', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'YZF 750', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'YZF R1', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'YZF R3', 1, 1)
GO INSERT INTO [dbo].[Veiculos] ([TipoCodigo], [MarcaCodigo], [Modelo], [UsuarioCriacao], [UsuarioAlteracao]) VALUES (2, 19, 	'YZF R6', 1, 1)
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (1, 'Audi')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (2, 'BMW')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (3, 'Chevrolet')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (4, 'Citröen')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (5, 'Fiat')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (6, 'Ford')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (7, 'Honda')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (8, 'Hyundai')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (9, 'Jeep	')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (10,'Kia')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (11,'Mitsubishi')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (12,'Nissan')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (13,'Peugeot')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (14,'Renault')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (15,'Toyota')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (16,'Volkswagen')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (17,'Dafra')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (18,'Suzuki')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (19,'Yamaha')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (20,'Kawasaki')
GO INSERT INTO [dbo].[Marcas] ([Codigo], [Nome]) VALUES (21,'Ducati')